# Generated by Django 4.0.4 on 2022-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordname', models.CharField(default='', max_length=255, unique=True)),
                ('def_noun', models.TextField(default='')),
                ('def_verb', models.TextField(default='')),
                ('def_adverb', models.TextField(default='')),
                ('def_adjective', models.TextField(default='')),
            ],
        ),
    ]
